# Generated by Django 2.2.3 on 2019-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=10000, null=True)),
                ('duty', models.TextField(blank=True, max_length=10000, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, max_length=10000, null=True)),
                ('site_id', models.CharField(max_length=127)),
            ],
        ),
    ]
