# Generated by Django 2.2.3 on 2019-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractvacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='specialisation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='site_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
