# Generated by Django 2.2.3 on 2019-07-28 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractvacancy', '0002_auto_20190727_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 7, 28, 12, 9, 34, 749580)),
        ),
    ]
